### ISSUE TITLE
uncover learn had a new problem

### ISSUE THREAD

**Issue by zhang01GA** [GeoscienceAustralia/hiperseis#110]
Today I pulled master branch and run uncoverml learn. But had a problem.
(It was running OK last week)

Ch
fxz547@vdi-n6 /g/data1a/ha3/fxz547/Githubz/uncover-ml/tmp_run/GA-cover2 (fei/uncoverml)
$ ~/.local/bin/uncoverml learn -p 10 demo_regression.yaml

Traceback (most recent call last):
  File "/home/547/fxz547/.local/bin/uncoverml", line 11, in <module>
    load_entry_point('uncover-ml', 'console_scripts', 'uncoverml')()
  File "/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/g/data1a/ha3/fxz547/Githubz/uncover-ml/uncoverml/scripts/uncoverml.py", line 62, in learn
    run_crossval(x_all, targets_all, config)
  File "/g/data1a/ha3/fxz547/Githubz/uncover-ml/uncoverml/scripts/uncoverml.py", line 50, in run_crossval
    ls.mpiops.run_once(ls.geoio.export_crossval, crossval_results, config)
  File "/g/data1a/ha3/fxz547/Githubz/uncover-ml/uncoverml/mpiops.py", line 46, in run_once
    f_result = f(*args, **kwargs)
  File "/g/data1a/ha3/fxz547/Githubz/uncover-ml/uncoverml/geoio.py", line 540, in export_crossval
    f.create_array("/", label, obj=v.data)
  File "/home/547/fxz547/.local/lib/python3.6/site-packages/tables/file.py", line 1152, in create_array
    flavor = flavor_of(obj)
  File "/home/547/fxz547/.local/lib/python3.6/site-packages/tables/flavor.py", line 198, in flavor_of
    "supported objects are: %s" % (type_name, supported_descs))
TypeError: objects of type ``memoryview`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes

**Comment by basaks** [comment]
Hi @zhang01GA,
I have check in my local (ubuntu 18.04) and our shared nci environment and confirmed that this is not a problem in either environment.

Seems like you are using anaconda. We don't support anaconda as it's does not work for multi-node computation in NCI. This is likely being caused by the anaconda environment. 

Please create a python virtualenv as per the instructions in the [here](https://github.com/GeoscienceAustralia/uncover-ml/tree/master/pbs). Otherwise you are welcome to use the uncoverml python enviroment we maintain for general use in NCI. It can be activated by using something like this:
```
module unload intel-cc
module unload intel-cc
module load python3/3.5.2 python3/3.5.2-matplotlib
module load hdf5/1.8.10 gdal/2.1.3 geos/3.5.0 gcc/4.9.0
module load openmpi/1.8
export LC_ALL=en_AU.UTF-8
export LANG=en_AU.UTF-8
source /g/data/ge3/john/venvs/class/bin/activate
```

**Comment by basaks** [comment]
Or alternatively, [you could follow this instruction](https://github.com/GeoscienceAustralia/uncover-ml/blob/master/pbs/README-nci-common-env.md).

**Comment by zhang01GA** [comment]
I'd like to run and develop uncoverml code in VDI, that's why we use anaconda python. 
If I use the shared virtual environment, is it the latest version of uncoverml? please confirm

**Comment by basaks** [comment]
Hi @zhang01GA , yes, the current nci env has the latest code. 

One convenient way develop is to use docker, and use the ci-image as the base image as in our [ci script](https://github.com/GeoscienceAustralia/uncover-ml/blob/master/.circleci/config.yml). 

Create a local virtualenv is also relatively easy in VDI. You could possibly [follow these instructions](https://gist.github.com/basaks/b33ea9106c7d1d72ac3a79fdcea430eb).

**Comment by zhang01GA** [comment]
Thank you @basaks . I will try your suggestion. However, I still suspect that anaconda may not be the root course, as the same problem observed in aws linux instance without using anaconda:

Traceback (most recent call last):
  File "/usr/local/bin/uncoverml", line 11, in <module>
    load_entry_point('uncover-ml', 'console_scripts', 'uncoverml')()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/uncover-ml/uncoverml/scripts/uncoverml.py", line 62, in learn
    run_crossval(x_all, targets_all, config)
  File "/home/ubuntu/uncover-ml/uncoverml/scripts/uncoverml.py", line 50, in run_crossval
    ls.mpiops.run_once(ls.geoio.export_crossval, crossval_results, config)
  File "/home/ubuntu/uncover-ml/uncoverml/mpiops.py", line 46, in run_once
    f_result = f(*args, **kwargs)
  File "/home/ubuntu/uncover-ml/uncoverml/geoio.py", line 540, in export_crossval
    f.create_array("/", label, obj=v.data)
  File "/**usr/local/lib/python3.5/dist-packages/tables-3.5.1-py3.5-linux-x86_64.egg/tables/file.py**", line 1152, in create_array
    flavor = flavor_of(obj)
  File "/usr/local/lib/python3.5/dist-packages/tables-3.5.1-py3.5-linux-x86_64.egg/tables/flavor.py", line 198, in flavor_of
    "supported objects are: %s" % (type_name, supported_descs))
TypeError: objects of type ``memoryview`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes

**Comment by zhang01GA** [comment]
I tried it on raijin and got the same error message:

Traceback (most recent call last):
  File "/g/data1a/ge3/john/venvs/class/bin/uncoverml", line 11, in <module>
    load_entry_point('uncover-ml', 'console_scripts', 'uncoverml')()
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data1a/ge3/john/uncover-ml/uncoverml/scripts/uncoverml.py", line 62, in learn
    run_crossval(x_all, targets_all, config)
  File "/g/data1a/ge3/john/uncover-ml/uncoverml/scripts/uncoverml.py", line 50, in run_crossval
    ls.mpiops.run_once(ls.geoio.export_crossval, crossval_results, config)
  File "/g/data1a/ge3/john/uncover-ml/uncoverml/mpiops.py", line 46, in run_once
    f_result = f(*args, **kwargs)
  File "/g/data1a/ge3/john/uncover-ml/uncoverml/geoio.py", line 540, in export_crossval
    f.create_array("/", label, obj=v.data)
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/tables-3.4.4-py3.5-linux-x86_64.egg/tables/file.py", line 1152, in create_array
    flavor = flavor_of(obj)
  File "/g/data1a/ge3/john/venvs/class/lib/python3.5/site-packages/tables-3.4.4-py3.5-linux-x86_64.egg/tables/flavor.py", line 198, in flavor_of
    "supported objects are: %s" % (type_name, supported_descs))
TypeError: objects of type ``memoryview`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes

### The test case is here: /g/data/ha3/fxz547/Githubz/uncover-ml/tmp_run/GA-cover2

**Comment by basaks** [comment]
what's the type of your v.data object ? 
Please copy the content of this demo and run it: /g/data/ge3/john/jobs/sirsam/rf_demo2.
If that demo works, problem is likely with your data.

**Comment by zhang01GA** [comment]
the v.data is not my part of program. It's all uncoverml's code. 
I think the best way is if you can acccess my dir and have a look of the yaml file.
It was from a long time ago. 

(class) fxz547@raijin5 /g/data/ha3/fxz547/Githubz/uncover-ml/tmp_run/GA-cover2 (fei/uncoverml) $ cat **demo_regression.ya**ml
features:
  - name: my features 1
    type: ordinal
    files:
      # - path: /g/data/ge3/feizhang/GA-cover2/Th_v1.tif
      # - list: /path/to/GA_data/GA_Cover2_sirsam_LLC/sirsam_covariates_convolved.txt
      - directory: /g/data/ge3/feizhang/GA-cover2
    # transforms are performed in order
    transforms:
      - centre
      - standardise
    imputation: none

  - name: my features 2
    type: categorical
    files:
      # - path: /path/to/GA_data/GA-cover2/Th_v1.tif
      - path: /g/data/ge3/feizhang/GA-cover2/Th_v1.tif
      # - list: /path/to/csv_file.csv
      # - directory: /g/data/ge3/feizhang/GA-cover2/cat_datasets
    # transforms are performed in order
    transforms:
      - randomhot:
          n_features: 10
          seed: 1
    imputation: none

# mask file used for masking prediction grid
# Mask with values=retain will be predicted
mask:
  file: /g/data/ge3/feizhang/GA-cover2/mask/old_mask_test.tif
  retain: 1

# imputation options are gaus, nn, mean
preprocessing:
  imputation: mean

  transforms:
    # - whiten:
        # keep_fraction: 0.8

targets:
  file: /g/data/ge3/feizhang/GA-cover2/geochem_sites.shp
  property: K_ppm_imp_

# target_transform: target transform (choice: stardardise, sqrt, log, identity,
# logistic, rank, kde)

learning:
    algorithm: svr
    arguments:
      target_transform: rank

# outbands: number of output bands desired.
# Bands (1:5): ['Prediction', 'Variance', 'Lower quantile',
# 'Upper quantile', 'Entropy']
prediction:
  quantiles: 0.95
  outbands: 1

validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: .

**Comment by basaks** [comment]
I suggest you start over with the demo I just provided. This directory has everything set up. If that works, there is nothing wrong.

**Comment by zhang01GA** [comment]
Mistake: This issue should have been discussed  in the uncoverml repo.
